version: '3'

services:
  twitter:
    container_name: twitter-dc
    image: likelion-cr-jh.kr.ncr.ntruss.com/twitter:latest #이미지 로컬에서 찾아서 사용
    ports:
      - 8000:8000
    volumes:
      - ~/.aws:/home/lion/.aws:ro
      - "staticfiles:/var/www/html/static"
    command:
      - "/start"
    env_file:
      - ./.envs/prod/django
      - ./.envs/prod/db
      - ./.envs/prod/server
    environment:
      - AWS_SECRET_NAME=like/lion/prod

  nginx:
    depends_on:
      - twitter
    container_name: twitter-nginx-dc
    build:
      context: .
      dockerfile: Dockerfile.nginx_ubt
    image: twitter-nginx
    ports:
      - "8888:80"
    volumes:
      - "staticfiles:/var/www/html/static"
    env_file:
      - ./.envs/prod/server

volumes:
  staticfiles:
  postgres_data: